<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVbAXV5F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVbAXV5F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVbAXV5F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVbAXV5F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVbAXV5F\App_KernelDevDebugContainer([
    'container.build_hash' => 'VbAXV5F',
    'container.build_id' => 'daf702aa',
    'container.build_time' => 1762349007,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVbAXV5F');
