<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5O8UAEx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5O8UAEx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5O8UAEx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5O8UAEx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5O8UAEx\App_KernelDevDebugContainer([
    'container.build_hash' => '5O8UAEx',
    'container.build_id' => '39a849ee',
    'container.build_time' => 1762771388,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5O8UAEx');
