<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrHxxhM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrHxxhM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKrHxxhM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKrHxxhM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKrHxxhM\App_KernelDevDebugContainer([
    'container.build_hash' => 'KrHxxhM',
    'container.build_id' => '47a86215',
    'container.build_time' => 1762496286,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrHxxhM');
